using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("Pattersonc")]
[assembly: AssemblyVersionAttribute("0.1.0.1")]
[assembly: AssemblyFileVersionAttribute("0.1.0.1")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.11672e3592db31e30b6389b181bb256b57bc01ab")]
[assembly: AssemblyTitleAttribute("ShowOff")]
[assembly: AssemblyProductAttribute("ShowOff")]
[assembly: AssemblyDescriptionAttribute("ShowOff is a product of Pattersonc - git://github.com/pattersonc/ShowOff.git.")]
[assembly: AssemblyTrademarkAttribute("ShowOff - Pattersonc")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010 Pattersonc, - Original author or authors")]

